/* oct format enums specific to the xbox 360 platform */
#pragma once

#ifndef __cplusplus

typedef enum xb_oct_elementType xb_oct_elementType;

#endif

/* Implements the xbox graphics types used by vertex elements and material properties */
enum xb_oct_elementType
{
    XBOX_OCT_ELEMENT_TYPE_FLOAT_ONE         = 0,    // R_FLOAT          | D3DDECLTYPE_FLOAT1    | DXGI_FORMAT_R32_FLOAT
    XBOX_OCT_ELEMENT_TYPE_FLOAT_TWO         = 1,    // RG_FLOAT         | D3DDECLTYPE_FLOAT2    | DXGI_FORMAT_R32G32_FLOAT
    XBOX_OCT_ELEMENT_TYPE_FLOAT_THREE       = 2,    // RGB_FLOAT        | D3DDECLTYPE_FLOAT3    | DXGI_FORMAT_R32G32B32_FLOAT
    XBOX_OCT_ELEMENT_TYPE_FLOAT_FOUR        = 3,    // RGBA_FLOAT       | D3DDECLTYPE_FLOAT4    | DXGI_FORMAT_R32G32B32A32_FLOAT
    XBOX_OCT_ELEMENT_TYPE_INT_ONE           = 10,   // R_SINT           | D3DDECLTYPE_INT1      | DXGI_FORMAT_R32_SINT
    XBOX_OCT_ELEMENT_TYPE_HALF_TWO_NORM     = 21,   // RG_HALF_NORM     | D3DDECLTYPE_SHORT2N   | DXGI_FORMAT_R16G16_SNORM
    XBOX_OCT_ELEMENT_TYPE_HALF_FOUR_NORM    = 23,   // RGBA_HALF_NORM   | D3DDECLTYPE_SHORT4N   | DXGI_FORMAT_R16G16B16A16_SNORM
    XBOX_OCT_ELEMENT_TYPE_UBYTE_FOUR        = 24,   // RGBA_U8          | D3DDECLTYPE_UBYTE4    | DXGI_FORMAT_R8G8B8A8_UINT
    XBOX_OCT_ELEMENT_TYPE_UBYTE_FOUR_NORM   = 25,   // RGBA_U8_NORM     | D3DDECLTYPE_UBYTE4N   | DXGI_FORMAT_R8G8B8A8_UNORM
    XBOX_OCT_ELEMENT_TYPE_PVEC_THREE        = 39,   // S10_S11_S11_FLOAT| Not Supported         | DXGI_FORMAT_R11G11B10_FLOAT
    XBOX_OCT_ELEMENT_TYPE_HALF_TWO          = 44,   // RG_HALF          | D3DDECLTYPE_FLOAT16_2 | DXGI_FORMAT_R16G16_FLOAT
    XBOX_OCT_ELEMENT_TYPE_HALF_FOUR         = 45,   // RGBA_HALF        | D3DDECLTYPE_FLOAT16_4 | DXGI_FORMAT_R16G16B16A16_FLOAT
};
